sudo: required
services: 
  - docker


before_install:
  - docker build -t johno/test -f Dockerfile.dev .

script:
  - docker run -e CI=true johno/test npm run test

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: "docker_react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-458041269140"
  bucket_path: "docker_react"

  on:
    branch: master
    access_key_id: $access-key\
    secret_access_key: $aws-secret\